name: hybrid-recommender
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.9.9=h06a4308_0
  - expat=2.7.1=h6a678d5_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - ncurses=6.5=h7934f7d_0
  - openssl=3.0.18=hd6dcaed_0
  - pip=25.2=pyhc872135_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.11.13=h1a3bd86_0
  - readline=8.3=hc2a1206_0
  - setuptools=78.1.1=py311h06a4308_0
  - sqlite=3.50.2=hb25bd0a_1
  - tk=8.6.15=h54e0aa7_0
  - tzdata=2025b=h04d1e81_0
  - wheel=0.45.1=py311h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - absl-py==2.3.1
      - astunparse==1.6.3
      - certifi==2025.8.3
      - charset-normalizer==3.4.3
      - flatbuffers==25.9.23
      - gast==0.6.0
      - google-pasta==0.2.0
      - grpcio==1.75.1
      - h5py==3.14.0
      - idna==3.10
      - joblib==1.5.2
      - keras==3.11.3
      - libclang==18.1.1
      - markdown==3.9
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - mdurl==0.1.2
      - ml-dtypes==0.5.3
      - namex==0.1.0
      - numpy==2.3.3
      - opt-einsum==3.4.0
      - optree==0.17.0
      - packaging==25.0
      - pillow==11.3.0
      - protobuf==6.32.1
      - pygments==2.19.2
      - requests==2.32.5
      - rich==14.1.0
      - scikit-learn==1.7.2
      - scipy==1.16.2
      - six==1.17.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.20.0
      - termcolor==3.1.0
      - threadpoolctl==3.6.0
      - typing-extensions==4.15.0
      - urllib3==2.5.0
      - werkzeug==3.1.3
      - wrapt==1.17.3
prefix: /home/lucas-couto/anaconda3/envs/hybrid-recommender
